name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        alias: [test, test-rc11]
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: latest
      - run: clojure -M:${{ matrix.alias }}
